# example netlify.toml
[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "vite"  # Adjust this if needed to match your dev server command
  port = 3000
  publish = "dist"  # Folder with the static content for _redirect file
